write_value:
  fields:
    endpoint_url:
      required: true
      selector:
        text:
    value:
      required: true
      selector:
        text:
    begin:
     required: false
     selector:
      number:
       min: 0
       max: 96
       mode: box
    end:
     required: false
     selector:
      number:
       min: 0
       max: 96
       mode: box
write_value_scaled:
  target:
    entity:
      integration: eta_webservices
      domain: number
  fields:
    value:
      required: true
      selector:
        number:
          step: 0.1
    force_decimals:
      required: true
      selector:
        boolean: